name: cognite_flutter_demo
description: A demo application for Cognite CDF
homepage: https://github.com/gregertw/cognite_flutter_demo
version: 0.5.4+9
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  oauth2_client: ^3.0.0
  cupertino_icons: ^1.0.3
  meta: ^1.7.0
  http: ^0.13.5
  dio: ^4.0.6
  logger: ^1.1.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  firebase_core: ^2.4.0
  firebase_analytics: ^10.0.7
  firebase_crashlytics: ^3.0.7
  overlay_support: ^2.1.0
  url_launcher: ^6.1.7
  cognite_cdf_sdk: ^0.2.0
  syncfusion_flutter_charts: ^20.3.60
  syncfusion_flutter_core: ^20.3.60
  syncfusion_flutter_sliders: ^20.3.60

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.1
  test: ^1.21.4
  flutter_launcher_icons: ^0.11.0
  convert: ^3.0.1
  mockito: ^5.0.16

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/actingweb-header-small.png
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/Nunito.ttf

  # Enable generation of localized Strings from arb file AppLocalizations.
  generate: true
